### ISSUE TITLE
Resource files not included in TestApp

### ISSUE THREAD

**Issue by YukinoHayakawa** [LinkClinton/GalDesigner#1]
Resource\ev09a.bmp
Resource\window.png
Resource\window_frame.png
Resource\window_menu.png

**Comment by LinkClinton** [comment]
I am sorry. The resource is only used for test. So I do not commit and I can save memory, too(in fact, the resource is not suited to public).
 Now the game engine is remaking, see the remake branch for more.

**Comment by YukinoHayakawa** [comment]
Good to know. Keep working.

**Comment by YukinoHayakawa** [comment]
加个qq呗 号发你邮箱啦

**Comment by LinkClinton** [comment]
突然中文.JPG
